import { StyleSheet } from "react-native";

import { theme } from "../../global/styles/theme";

export const styles = StyleSheet.create({
  container_a: {
    flex: 1,
    paddingTop: 40,
    justifyContent: "center",
    alignItems: "center",
  },
  container_b: {
    flex: 1,
    paddingTop: 40,
    backgroundColor: theme.colors.white,
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    flexDirection: "row",
  },
  container_c: {
    backgroundColor: theme.colors.white,
    paddingTop: 40,
    display: "flex",
    justifyContent: "space-between",
    flexDirection: "row",
  },
  container_d: {
    flex: 1,
    paddingTop: 10,
    backgroundColor: theme.colors.white,
    display: "flex",
    justifyContent: "space-evenly",
    alignItems: "center",
    flexDirection: "row",
  },
  separate: {
    flex: 1,
    paddingTop: 10,
    backgroundColor: theme.colors.white,
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    flexDirection: "row",
  },
  container_e: {
    paddingLeft: 25,
    paddingRight: 25,
    backgroundColor: theme.colors.white,
  },
  image_a: {
    width: "100%",
    height: 360,
  },
  image_b: {
    width: 40,
    height: 30,
  },
  image_c: {
    width: "100%",
    height: 200,
  },
  image_d: {
    flex: 1,
    marginLeft: 40,
    width: "50%",
    height: 50,
    alignItems: "center",
  },
  image_e: {
    width: 25,
    height: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  image_f: {
    flex: 1,
    maxWidth: 100,
    height: 100,
    alignItems: "center",
  },
  image_g: {
    backgroundColor: "gray",
    height: 100,
    width: 100,
    maxHeight: 100,
    maxWidth: 100,
  },
  imageLogo: {
    marginTop: 20,
    marginBottom: 30,
  },
  content: {
    marginTop: -50,
    paddingHorizontal: 50,
  },
  title: {
    color: theme.colors.heading,
    textAlign: "center",
    fontWeight: "bold",
    fontSize: 40,
    marginBottom: 16,
    fontFamily: theme.fonts.title700,
    lineHeight: 40,
  },
  subtitle: {
    color: theme.colors.heading,
    fontSize: 20,
    textAlign: "center",
    marginBottom: 10,
    fontFamily: theme.fonts.title500,
    lineHeight: 25,
  },
  subtitle_a: {
    color: theme.colors.text,
    fontSize: 20,
    textAlign: "center",
    marginBottom: 10,
    fontFamily: theme.fonts.title500,
    lineHeight: 25,
    marginLeft: 20,
  },
  subtitle_b: {
    color: theme.colors.text,
    fontSize: 14,
    textAlign: "center",
    marginBottom: 10,
    lineHeight: 25,
  },
  red: {
    color: "red",
    marginTop: 20,
  },
  subtitle_c: {
    color: theme.colors.text,
    fontSize: 20,
    textAlign: "left",
    marginBottom: 10,
    fontFamily: theme.fonts.text500,
  },
  subtitle_d: {
    color: theme.colors.secundary,
    fontSize: 14,
    textAlign: "left",
    marginBottom: 10,
    fontFamily: theme.fonts.text500,
  },
  title_a: {
    color: theme.colors.text,
    fontWeight: "bold",
    fontSize: 25,
    marginLeft: 20,
  },
  linha: {
    borderBottomColor: "#d3d3d3",
    borderBottomWidth: 2,
  },
  buttons: {
    width: "100%",
    height: 56,
    backgroundColor: theme.colors.secondary100,
    borderRadius: 15,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-evenly",
  },
  icons: {
    display: "flex",
    justifyContent: "space-between",
    flexDirection: "row",
  },
  controlsbutons: {
    marginTop: 30,
    width: "100%",
    paddingHorizontal: 35,
    paddingBottom: 30,
  },
});
